#!/usr/bin/env python3
"""
Building Machine Learning Powered Applications Chapter 6: Debug Your ML Problems
"""
import pytest
import sys
if '../' not in sys.path:
    sys.path.append('../')
import joblib
import pandas as pd
from helper_functions import format_raw_df, add_text_features, add_features, get_vectorised_series, \
    get_feature_vectors_and_labels
from scipy.sparse import vstack, hstack

FEATURE_NAMES = ['question_mark_full', 'question_word_full', 'action_verb_full', 'text_length']

@pytest.fixture
def df_with_features():
    df = pd.read_csv('../Data Science Posts.csv')
    df = format_raw_df(df.copy())
    return add_features(df.copy())

@pytest.fixture
def fitted_vectoriser():
    vectoriser = joblib.load('../Models/Vectoriser_v1.pkl')
    return vectoriser

@pytest.fixture
def pretrained_model():
    classifier = joblib.load('../Models/Model_v1.pkl')
    return classifier

def test_model_prediction_dimensions(df_with_features, fitted_vectoriser, pretrained_model):
    df_with_features['vectors'] = get_vectorised_series(df_with_features['full_text'].copy(),
                                                        fitted_vectoriser)
    features, labels = get_feature_vectors_and_labels(df_with_features, FEATURE_NAMES)

    probabilities = pretrained_model.predict_proba(features)
    # Check that the model makes one prediction per input example
    assert probabilities.shape[0] == features.shape[0]
    # Check that the model predicts probabilities for two classes
    assert probabilities.shape[1] == 2

def test_model_probability_values(df_with_features, fitted_vectoriser, pretrained_model):
    df_with_features['vectors'] = get_vectorised_series(df_with_features['full_text'].copy(),
                                                        fitted_vectoriser)
    features, labels = get_feature_vectors_and_labels(df_with_features, FEATURE_NAMES)

    probabilities = pretrained_model.predict_proba(features)
    # Check that the probabilities generated by the model are between 0 and 1, inclusive
    assert (probabilities >= 0).all() and (probabilities <= 1).all()

def test_model_predictions(fitted_vectoriser, pretrained_model):
    input_text = "This isn't even a question. We should score it poorly."
    df = pd.DataFrame([input_text], columns = ['full_text'])
    df = add_text_features(df)
    df['vectors'] = get_vectorised_series(df['full_text'].copy(), fitted_vectoriser)
    vectorised_features = vstack(df['vectors'])
    added_features = df[FEATURE_NAMES].astype(float)
    features = hstack([vectorised_features, added_features])

    probabilities = pretrained_model.predict_proba(features)
    predicted_classes = probabilities[:, 0] < probabilities[:, 1]
    assert not predicted_classes[0]